### ISSUE TITLE
notify users of job status

### ISSUE THREAD

**Issue by g-k** [mozilla-platform-ops/relops-hardware-controller#26]
It'd be nice to have a way to show an running action's status and errors in the TC dashboard.

Possible options:

* [websockets](https://developer.mozilla.org/en-US/docs/Web/API/Websockets_API)
* [sse](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events)
* long-polling/comet
* polling

**Comment by g-k** [comment]
@helfi92 any recommendations for this?

**Comment by helfi92** [comment]
Hey @g-k, right now we currently `await` on the action request and show a green banner if the request resolves without throwing. If the user is missing scopes, then we show an error. 

There isn't something in place right now to show a real-time update of a request status. If the request takes 10 seconds for example, then there will be a loading spinner until that request returns something. I'm not sure we want to handle continuous status update for now since we'll be dealing with many different domains.

You can see https://github.com/taskcluster/taskcluster-tools/blob/master/src/views/WorkerManager/WorkerManager.js#L169-L199 for the method where we handle the request. Hope that helps.

**Comment by helfi92** [comment]
@g-k To notify users with the action status, you could look into [taskcluster-notify](https://github.com/taskcluster/taskcluster-notify).

**Comment by helfi92** [comment]
Also, it's better if the action endpoint returns early. In other words, if the action takes a while, start it up and send the HTTP response.

**Comment by helfi92** [comment]
@g-k To interact with the taskcluster-notify service, use [taskcluster/taskcluster-client#methods-in-taskclusternotify](https://github.com/taskcluster/taskcluster-client#methods-in-taskclusternotify).

**Comment by g-k** [comment]
+1 for notifications. These will probably take >10 seconds run.
